### ISSUE TITLE
GA Connector is getting error.

### ISSUE THREAD

**Issue by sanjusci** [MrTrustworthy/kafka-connect-googleanalytics#4]
[WARNING] useSystemClassloader setting has no effect when not forking
Running org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.522 sec <<< FAILURE! - in org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest
testAnalyticsReportingInitialization()  Time elapsed: 0.473 sec  <<< ERROR!
com.fasterxml.jackson.core.JsonParseException:
Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
 at [Source: java.io.ByteArrayInputStream@31973858; line: 6, column: 16]
	at org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest.testAnalyticsReportingInitialization(GAReportFetcherTest.java:46)

testStructAssembly()  Time elapsed: 0.006 sec  <<< ERROR!
kafka.common.KafkaException:
Error starting task, could not initialize AnalyticsReporting: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
 at [Source: java.io.ByteArrayInputStream@603cabc4; line: 6, column: 16]
	at org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest.testStructAssembly(GAReportFetcherTest.java:62)

Results :

Tests in error:
  GAReportFetcherTest.testAnalyticsReportingInitialization:46 » JsonParse Unexpe...
  GAReportFetcherTest.testStructAssembly:62 » Kafka Error starting task, could n...

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

**Comment by sanjusci** [comment]
> [WARNING] useSystemClassloader setting has no effect when not forking
> Running org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest
> Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.522 sec <<< FAILURE! - in org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest
> testAnalyticsReportingInitialization() Time elapsed: 0.473 sec <<< ERROR!
> com.fasterxml.jackson.core.JsonParseException:
> Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
> at [Source: java.io.ByteArrayInputStream@31973858; line: 6, column: 16]
> at org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest.testAnalyticsReportingInitialization(GAReportFetcherTest.java:46)
> 
> testStructAssembly() Time elapsed: 0.006 sec <<< ERROR!
> kafka.common.KafkaException:
> Error starting task, could not initialize AnalyticsReporting: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
> at [Source: java.io.ByteArrayInputStream@603cabc4; line: 6, column: 16]
> at org.MrTrustworthy.kafka.connect.googleanalytics.source.GAReportFetcherTest.testStructAssembly(GAReportFetcherTest.java:62)
> 
> Results :
> 
> Tests in error:
> GAReportFetcherTest.testAnalyticsReportingInitialization:46 » JsonParse Unexpe...
> GAReportFetcherTest.testStructAssembly:62 » Kafka Error starting task, could n...
> 
> Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

**Comment by sanjusci** [comment]
++
